//! `.env` compatibility.

use std::collections::BTreeMap;
use std::path::Path;

use kivro_core::{Error, Result, SecretName, SecretString};

/// Outcome of parsing a `.env` file.
#[derive(Debug, Default)]
pub struct EnvFile {
    /// Entries whose keys are valid secret names.
    pub entries: BTreeMap<SecretName, SecretString>,
    /// Keys that were skipped because they are not valid secret names,
    /// with the line they appeared on. Reported, never silently dropped.
    pub skipped: Vec<(String, usize)>,
}

/// Parse `.env` text.
pub fn parse(path: &Path, text: &str) -> Result<EnvFile> {
    let mut out = EnvFile::default();

    for (index, raw_line) in text.lines().enumerate() {
        let line_no = index + 1;
        let line = raw_line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }

        let line = line.strip_prefix("export ").unwrap_or(line).trim_start();
        let Some((key, value)) = line.split_once('=') else {
            return Err(Error::EnvFormat {
                path: path.to_path_buf(),
                line: line_no,
                message: "expected `KEY=value`".into(),
            });
        };

        let key = key.trim();
        if key.is_empty() {
            return Err(Error::EnvFormat {
                path: path.to_path_buf(),
                line: line_no,
                message: "empty variable name".into(),
            });
        }

        let value = parse_value(value.trim()).ok_or_else(|| Error::EnvFormat {
            path: path.to_path_buf(),
            line: line_no,
            message: "unterminated quoted value".into(),
        })?;

        match SecretName::new(key) {
            Ok(name) => {
                out.entries.insert(name, SecretString::new(value));
            }
            Err(_) => out.skipped.push((key.to_string(), line_no)),
        }
    }

    Ok(out)
}

fn parse_value(raw: &str) -> Option<String> {
    let mut chars = raw.chars().peekable();
    match chars.peek() {
        Some('"') => {
            chars.next();
            let mut out = String::new();
            loop {
                match chars.next()? {
                    '"' => return Some(out),
                    '\\' => match chars.next()? {
                        'n' => out.push('\n'),
                        'r' => out.push('\r'),
                        't' => out.push('\t'),
                        other => out.push(other),
                    },
                    c => out.push(c),
                }
            }
        }
        Some('\'') => {
            chars.next();
            let mut out = String::new();
            loop {
                match chars.next()? {
                    '\'' => return Some(out),
                    c => out.push(c),
                }
            }
        }
        _ => {
            let value = match raw.find(" #") {
                Some(at) => &raw[..at],
                None => raw,
            };
            Some(value.trim_end().to_string())
        }
    }
}

/// render secrets to a .env string
pub fn render(entries: &BTreeMap<SecretName, SecretString>) -> String {
    let mut out = String::from(
        "# Generated by `kivro export`.\n\
         # WARNING: this file contains plaintext secrets. Do not commit it.\n\n",
    );
    for (name, value) in entries {
        out.push_str(name.as_str());
        out.push_str("=\"");
        for c in value.expose_secret().chars() {
            match c {
                '"' => out.push_str("\\\""),
                '\\' => out.push_str("\\\\"),
                '\n' => out.push_str("\\n"),
                '\r' => out.push_str("\\r"),
                '\t' => out.push_str("\\t"),
                c => out.push(c),
            }
        }
        out.push_str("\"\n");
    }
    out
}

/// Heuristic: does this file look like it holds real secrets
pub fn looks_like_secrets(text: &str) -> bool {
    text.lines()
        .filter(|l| {
            let l = l.trim();
            !l.is_empty() && !l.starts_with('#')
        })
        .filter_map(|l| l.split_once('='))
        .any(|(_, v)| {
            let v = v.trim().trim_matches(['"', '\''].as_slice());
            v.len() >= 8 && !v.starts_with("${") && !matches!(v, "changeme" | "replace-me")
        })
}

#[cfg(test)]
mod tests {
    use super::*;

    fn p(text: &str) -> EnvFile {
        parse(Path::new(".env"), text).unwrap()
    }

    fn get(f: &EnvFile, name: &str) -> String {
        f.entries[&SecretName::new(name).unwrap()]
            .expose_secret()
            .to_string()
    }

    #[test]
    fn parses_the_common_shapes() {
        let f =
            p("# comment\n\nA=1\nexport B=two\nC = spaced \nD=\"quoted value\"\nE='raw $NOPE'\n");
        assert_eq!(get(&f, "A"), "1");
        assert_eq!(get(&f, "B"), "two");
        assert_eq!(get(&f, "C"), "spaced");
        assert_eq!(get(&f, "D"), "quoted value");
        assert_eq!(get(&f, "E"), "raw $NOPE");
    }

    #[test]
    fn handles_escapes_and_inline_comments() {
        let f = p("A=\"line1\\nline2\"\nB=value # trailing\nC=pass#word\nD=\"has # hash\"\n");
        assert_eq!(get(&f, "A"), "line1\nline2");
        assert_eq!(get(&f, "B"), "value");
        assert_eq!(get(&f, "C"), "pass#word");
        assert_eq!(get(&f, "D"), "has # hash");
    }

    #[test]
    fn empty_values_are_preserved() {
        let f = p("A=\nB=\"\"\n");
        assert_eq!(get(&f, "A"), "");
        assert_eq!(get(&f, "B"), "");
    }

    #[test]
    fn unusable_keys_are_reported_not_dropped_silently() {
        let f = p("lower_case=1\nGOOD=2\n");
        assert_eq!(f.entries.len(), 1);
        assert_eq!(f.skipped, vec![("lower_case".to_string(), 1)]);
    }

    #[test]
    fn malformed_lines_are_rejected_with_a_line_number() {
        let err = parse(Path::new(".env"), "GOOD=1\nnonsense\n").unwrap_err();
        assert!(err.to_string().contains("line 2"));
        let err = parse(Path::new(".env"), "A=\"unterminated\n").unwrap_err();
        assert!(err.to_string().contains("unterminated"));
    }

    #[test]
    fn render_round_trips_through_parse() {
        let mut entries = BTreeMap::new();
        entries.insert(
            SecretName::new("TRICKY").unwrap(),
            SecretString::new("a\"b\\c\nd\te #f"),
        );
        entries.insert(SecretName::new("SIMPLE").unwrap(), SecretString::new("1"));
        let text = render(&entries);
        let back = parse(Path::new(".env"), &text).unwrap();
        assert_eq!(back.entries, entries);
        assert!(text.contains("WARNING"));
    }

    #[test]
    fn detects_files_that_look_like_secrets() {
        assert!(looks_like_secrets("AUTH0_CLIENT_SECRET=8f3a9c2b1d4e5f60\n"));
        assert!(!looks_like_secrets("# just a comment\nPORT=3000\n"));
        assert!(!looks_like_secrets("API_URL=${OTHER}\n"));
    }
}
